#!/bin/bash
find . -name '*.c' -o -name '*.h' -o -name '*.tcl' -o -name '*.hxx' -o -name '*.cxx' -o -name '*.cc'|grep -v "~" | grep -v ".l.cc" |grep -v ".y.cc" | grep -v ".#"|grep -v ".cache" > cscope.files
cscope -b -q -k -i cscope.files;
