#!/bin/sh

# Uncomment the following two lines for normal desktop:
if [ `uname` = "Linux" ]; then
	unset SESSION_MANAGER
	exec /etc/X11/xinit/xinitrc

	[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
	[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
	xsetroot -solid grey
	vncconfig -iconic &
	xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
	startx &

elif [ `uname` = "SunOS" ]; then

	[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
	xsetroot -solid grey
	xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
	/usr/dt/bin/dtwm &

fi
